import { sql } from "drizzle-orm";
import {
  pgTable,
  text,
  varchar,
  integer,
  boolean,
  timestamp,
  jsonb,
  date,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export * from "./models/auth";

export const artists = pgTable("artists", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  bio: text("bio"),
  genre: text("genre").notNull(),
  avatarUrl: text("avatar_url"),
  coverUrl: text("cover_url"),
  monthlyListeners: integer("monthly_listeners").default(0),
  totalPlays: integer("total_plays").default(0),
  isVerified: boolean("is_verified").default(false),
  isSigned: boolean("is_signed").default(false),
  status: text("status").default("pending"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const tracks = pgTable("tracks", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  title: text("title").notNull(),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  genre: text("genre").notNull(),
  duration: integer("duration").notNull(),
  audioUrl: text("audio_url"),
  coverUrl: text("cover_url"),
  plays: integer("plays").default(0),
  likes: integer("likes").default(0),
  isReleased: boolean("is_released").default(true),
  releaseDate: timestamp("release_date").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const playlists = pgTable("playlists", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  description: text("description"),
  coverUrl: text("cover_url"),
  userId: varchar("user_id"),
  isAutoGenerated: boolean("is_auto_generated").default(false),
  trackIds: text("track_ids").array().default(sql`'{}'::text[]`),
  createdAt: timestamp("created_at").defaultNow(),
});

export const userLikes = pgTable("user_likes", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull(),
  trackId: varchar("track_id").notNull().references(() => tracks.id),
  createdAt: timestamp("created_at").defaultNow(),
});

export const notifications = pgTable("notifications", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id"),
  title: text("title").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull(),
  isRead: boolean("is_read").default(false),
  relatedId: varchar("related_id"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const arRecommendations = pgTable("ar_recommendations", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  score: integer("score").notNull(),
  reason: text("reason").notNull(),
  status: text("status").default("pending"),
  reviewedBy: varchar("reviewed_by"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const promotions = pgTable("promotions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  trackId: varchar("track_id").references(() => tracks.id),
  artistId: varchar("artist_id").references(() => artists.id),
  title: text("title").notNull(),
  content: text("content").notNull(),
  platform: text("platform").notNull(),
  status: text("status").default("pending"),
  approvedBy: varchar("approved_by"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const userFollows = pgTable("user_follows", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull(),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  createdAt: timestamp("created_at").defaultNow(),
});

export const liveSessions = pgTable("live_sessions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  title: text("title").notNull(),
  description: text("description"),
  startsAt: timestamp("starts_at").notNull(),
  endsAt: timestamp("ends_at").notNull(),
  status: text("status").default("upcoming"),
  viewerCount: integer("viewer_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

export const artistDailyStats = pgTable("artist_daily_stats", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  date: date("date").notNull(),
  plays: integer("plays").default(0),
  followers: integer("followers").default(0),
  popularity: integer("popularity").default(0),
});

export const revenueDaily = pgTable("revenue_daily", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  trackId: varchar("track_id").references(() => tracks.id),
  date: date("date").notNull(),
  streams: integer("streams").default(0),
  revenue: integer("revenue_cents").default(0),
});

export const contentCalendar = pgTable("content_calendar", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  artistId: varchar("artist_id").notNull().references(() => artists.id),
  trackId: varchar("track_id").references(() => tracks.id),
  title: text("title").notNull(),
  type: text("type").notNull(),
  platform: text("platform"),
  scheduledAt: timestamp("scheduled_at").notNull(),
  status: text("status").default("pending"),
  aiNotes: text("ai_notes"),
  approvedBy: varchar("approved_by"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertArtistSchema = createInsertSchema(artists).omit({
  id: true,
  createdAt: true,
});
export const insertTrackSchema = createInsertSchema(tracks).omit({
  id: true,
  createdAt: true,
});
export const insertPlaylistSchema = createInsertSchema(playlists).omit({
  id: true,
  createdAt: true,
});
export const insertNotificationSchema = createInsertSchema(notifications).omit({
  id: true,
  createdAt: true,
});
export const insertPromotionSchema = createInsertSchema(promotions).omit({
  id: true,
  createdAt: true,
});

export const insertLiveSessionSchema = createInsertSchema(liveSessions).omit({
  id: true,
  createdAt: true,
});
export const insertArtistDailyStatsSchema = createInsertSchema(artistDailyStats).omit({
  id: true,
});

export type Artist = typeof artists.$inferSelect;
export type InsertArtist = z.infer<typeof insertArtistSchema>;
export type Track = typeof tracks.$inferSelect;
export type InsertTrack = z.infer<typeof insertTrackSchema>;
export type Playlist = typeof playlists.$inferSelect;
export type InsertPlaylist = z.infer<typeof insertPlaylistSchema>;
export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;
export type ARRecommendation = typeof arRecommendations.$inferSelect;
export type Promotion = typeof promotions.$inferSelect;
export type InsertPromotion = z.infer<typeof insertPromotionSchema>;
export type UserFollow = typeof userFollows.$inferSelect;
export type UserLike = typeof userLikes.$inferSelect;
export type LiveSession = typeof liveSessions.$inferSelect;
export type InsertLiveSession = z.infer<typeof insertLiveSessionSchema>;
export type ArtistDailyStat = typeof artistDailyStats.$inferSelect;

export const insertRevenueDailySchema = createInsertSchema(revenueDaily).omit({ id: true });
export const insertContentCalendarSchema = createInsertSchema(contentCalendar).omit({ id: true, createdAt: true });

export type RevenueDaily = typeof revenueDaily.$inferSelect;
export type InsertRevenueDaily = z.infer<typeof insertRevenueDailySchema>;
export type ContentCalendarItem = typeof contentCalendar.$inferSelect;
export type InsertContentCalendarItem = z.infer<typeof insertContentCalendarSchema>;

export const agents = pgTable("agents", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  role: text("role").notNull(),
  description: text("description"),
  capabilities: text("capabilities").array().default(sql`'{}'::text[]`),
  assignedUnit: text("assigned_unit"),
  status: text("status").default("active"),
  lastActiveAt: timestamp("last_active_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const agentTasks = pgTable("agent_tasks", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  agentId: varchar("agent_id").references(() => agents.id),
  title: text("title").notNull(),
  description: text("description"),
  taskType: text("task_type").notNull(),
  priorityScore: integer("priority_score").default(50),
  status: text("status").default("pending"),
  requiresApproval: boolean("requires_approval").default(true),
  approvedBy: varchar("approved_by"),
  dueAt: timestamp("due_at"),
  expectedOutcome: text("expected_outcome"),
  businessImpact: text("business_impact"),
  urgency: text("urgency").default("medium"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const executionRuns = pgTable("execution_runs", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  agentId: varchar("agent_id").references(() => agents.id),
  taskId: varchar("task_id").references(() => agentTasks.id),
  startTime: timestamp("start_time").notNull(),
  endTime: timestamp("end_time"),
  totalDurationMs: integer("total_duration_ms"),
  status: text("status").default("running"),
  actionLog: text("action_log").array().default(sql`'{}'::text[]`),
  outputSummary: text("output_summary"),
  qualityScore: integer("quality_score"),
  objectiveMet: text("objective_met"),
  lessonsLearned: text("lessons_learned"),
  nextSteps: text("next_steps"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const agentMemory = pgTable("agent_memory", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  agentId: varchar("agent_id").references(() => agents.id),
  taskId: varchar("task_id").references(() => agentTasks.id),
  insight: text("insight").notNull(),
  category: text("category").notNull(),
  qualityScore: integer("quality_score"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAgentSchema = createInsertSchema(agents).omit({ id: true, createdAt: true });
export const insertAgentTaskSchema = createInsertSchema(agentTasks).omit({ id: true, createdAt: true });
export const insertExecutionRunSchema = createInsertSchema(executionRuns).omit({ id: true, createdAt: true });
export const insertAgentMemorySchema = createInsertSchema(agentMemory).omit({ id: true, createdAt: true });

export type Agent = typeof agents.$inferSelect;
export type InsertAgent = z.infer<typeof insertAgentSchema>;
export type AgentTask = typeof agentTasks.$inferSelect;
export type InsertAgentTask = z.infer<typeof insertAgentTaskSchema>;
export type ExecutionRun = typeof executionRuns.$inferSelect;
export type InsertExecutionRun = z.infer<typeof insertExecutionRunSchema>;
export type AgentMemory = typeof agentMemory.$inferSelect;
export type InsertAgentMemory = z.infer<typeof insertAgentMemorySchema>;
